all: 1 2 3 4 5 6 7

1: src/1.c 
	gcc src/1.c -o bin/1 -lpthread

2: src/2.c 
	gcc src/2.c -o bin/2 -lpthread

3: src/3.c 
	gcc src/3.c -o bin/3 -lpthread

4: src/4.c 
	gcc src/4.c -o bin/4 -lpthread

5: src/5.c 
	gcc src/5.c -o bin/5 -lpthread

6: src/6.c 
	gcc src/6.c -o bin/6 -lpthread

7: src/7.c 
	gcc src/7.c -o bin/7 -lpthread

8: src/8.c 
	gcc src/8.c -o bin/8 -lpthread

clean:
	rm -f bin/*
